// Imported verbatim from maplekiosk.ca/terms and /privacy (English only there too)
export const TERMS_TITLE =
  "MapleKiosk End-User License Agreement"
export const TERMS_DATE = "Last updated: July 22, 2026"
export const TERMS_HTML = `
<p>This End-User License Agreement (<strong>Agreement</strong>) is between the business or individual accepting this Agreement (this business or individual being <strong>you/Merchant</strong>) and MapleKiosk Inc. (<strong>Developer/App Provider</strong>). This Agreement is solely between you and Developer/App Provider, and governs your use of Developer's software application and the corresponding services it provides (together, along with the associated documentation, proprietary, or intellectual property: the <strong>App</strong>). Review this Agreement completely. <strong>You agree to be bound by the terms of this Agreement when you click "Accept" or otherwise download, install, copy, or use the App, and must accept this Agreement before doing so.</strong> If you do not agree to the terms of this Agreement, you must click "Decline" and must not download, install, copy or use the App.</p>
<h2>1. The App</h2>
<p>1.1 The App will provide you with the ability to: run MapleKiosk's family of business applications and AI services on the Clover Point of Sale system, including product and menu catalog management, order and checkout management, appointment and reservation booking, and AI-assisted phone and web-chat reception and booking assistance. Payment card processing is performed by Clover and its payment processors, not by MapleKiosk.</p>
<p>1.2 Developer grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license during the Term (defined below) of this Agreement to use the App solely for your internal business purposes. You will not otherwise distribute, lease, rent, host, sublicense, transfer, sell, export, modify, reverse engineer, decompile, copy, benchmark, create derivative works from, or attempt to derive the source code for the App. This license does not grant you any rights to Developer's (or any other third party's) trademarks, service marks, logos, trade dress, proprietary, or other intellectual property unless provided with the App. Developer reserves to itself (or applicable third parties) all right, title, interest, and license (express or implied) to the App that are not specifically granted to you under this Agreement. You will preserve and display any proprietary notices, markings, or branding associated with use of the App.</p>
<p>1.3 The App may update automatically from time-to-time, and you may be required to accept these updates to continue using the App. Developer may perform maintenance on the App, which may result in service interruptions or delays from time to time. Developer may not support older versions of the App. You are solely responsible for obtaining all equipment and services (for example, Internet connectivity) necessary to access and use the App.</p>
<h2>2. Fees</h2>
<p>You will pay the Developer a monthly fee for your use of the App, which will be automatically collected through the payment method you select during set-up for the App. You are responsible for payment of all sales, use, excise, or similar taxes (excluding taxes based on the Developer's income) imposed by federal, state, or local tax authority. You must notify the Developer of any billing errors within 120 days from when an error appears on your invoice, after which you release the Developer from all liability for Losses (defined below) resulting from these errors.</p>
<h2>3. Term</h2>
<p>This Agreement commences when you accept or otherwise download, install, copy, or use the App; and will continue month-to-month until terminated (this period of time is the Agreement's <strong>Term</strong>).</p>
<h2>4. Suspension and Termination</h2>
<p>4.1 Developer may promptly suspend or terminate your use of the App if (1) you violate this Agreement's terms; (2) Developer believes your use of the App may damage its reputation or intellectual property rights; (3) Developer suspends or terminates its agreement(s) with any third party involved in providing the App; (4) you exceed normal and reasonable usage for the App; (5) you experience a bankruptcy or insolvency event; or (6) you are using the App for any fraudulent, illegal, or unauthorized purpose, or engage in willful misconduct with respect to use of the App.</p>
<p>4.2 You may terminate this Agreement at any time and for any reason (without cause) by providing notice to Developer. Your termination will be effective at the end of the then current month or billing period in which you give notice. You will not receive a refund for the billing period in which you terminate this Agreement.</p>
<h2>5. Confidentiality, Data, and Ideas</h2>
<p>5.1 Neither of us will disclose non-public information about the other's business; including, without limitation, the terms of this Agreement, technical specifications (whether related to the App or otherwise), customer lists, or information relating to a party's operational, strategic, or financial matters (together, <strong>Confidential Information</strong>). Confidential Information does not include information that (1) is or subsequently becomes publicly available (through no fault of the recipient); (2) the recipient lawfully possesses before its disclosure; (3) is independently developed without reliance on the discloser's Confidential Information; or (4) is received from a third party that is not obligated to keep it confidential. Each of us will implement and maintain reasonable safeguards to protect the other's Confidential Information.</p>
<p>5.2 Neither of us may disclose the other's Confidential Information except (1) to our respective directors, officers, employees, or representatives that need to know it in order to perform our obligations under this Agreement; (2) in response to a subpoena or court order; or (3) as required by applicable law, rule, or regulation.</p>
<p>5.3 Developer may use data or information obtained through the App to provide its services, for research and development, or in aggregated and anonymized form to provide services generally; all subject to applicable Laws (defined below). Information Developer collects about you or your consumers is subject to Developer's privacy policy, which is accessible at <a href="/confidentialite">maplekiosk.ca/privacy</a>.</p>
<p>5.4 You may provide, or Developer may invite you to provide, comments or ideas about the App (including, without limitation, improvements to it) (together, <strong>Ideas</strong>). By submitting any Ideas, you agree that (1) they are not Confidential Information; (2) they are not subject to any use or disclosure restrictions (express or implied); (3) you claim no rights in them; and (4) Developer has no obligation to notify or compensate you in connection with their disclosure or use. You release Developer from all liability or obligations that may arise from the receipt, review, disclosure, or use of any Idea that you submit.</p>
<h2>6. Account</h2>
<p>You will be required to register for an account with Developer to use the App. You will provide us with accurate information when setting-up your account, and will maintain your account with current information. You will be responsible for establishing safeguards designed to prevent unauthorized access to, disclosure, use, or alteration of your account (safeguards may include, without limitation, user names, passwords, security questions and answers, or other credentials). You must notify Developer if you discover a security breach involving your account or the App. You are responsible for any unauthorized access to, disclosure, use, or alteration of your account, the App, or other transaction information that arises through your systems or account. It is your responsibility to back-up and maintain the accuracy and completeness of any content created, derived from, stored, or accessed through your account or your use of the App (content may include, without limitation, transaction information, text, images, graphics, or photos).</p>
<h2>7. Risk Allocation</h2>
<p>7.1 The App is provided to you "as-is" and "as-available." You are solely responsible for determining if the App meets your needs. <strong>Developer disclaims all warranties (express or implied) related to your account or the App; including, without limitation, warranties of security, merchantability, fitness for a particular purpose, non-infringement, accuracy, and uninterrupted or error-free operation.</strong> Developer is not responsible for any disclosures, modifications, deletions, or other errors that arise in connection with your use of the App due to its interaction with other applications or their content.</p>
<p>7.2 You will indemnify Developer, its directors, officers, employees, agents, subsidiaries, and affiliates against any third-party claims for losses, damages, costs, or expenses (including reasonable attorneys' fees) (together, <strong>Losses</strong>) that result from your use or misuse of the App, or your breach of this Agreement. The developer may assume the defense of any third-party claims that you must indemnify it for (at your expense), and you will cooperate with the defense of these claims. You will not settle any third-party claims involving more than the payment of money without Developer's written consent.</p>
<p>7.3 <strong>To the extent permitted by applicable law, Developer will not be liable to you for any lost profits, revenues, or business opportunities, nor any exemplary, punitive, special, indirect, incidental, or consequential damages; regardless of whether these damages were foreseeable or either of us was advised they were possible.</strong></p>
<p>7.4 <strong>Developer's total, aggregate liability to you for all Losses arising from any cause (regardless of the form of action or legal theory) in connection with this Agreement will not exceed the amount of fees you've paid to Developer during the 3 months prior to a Loss.</strong></p>
<h2>8. Communications</h2>
<p>You authorized Developer to communicate with you electronically or otherwise using the contact information you provide to it (e.g., without limitation, via your account, the Internet, email, text, or live agent or automated calls to your mobile or other phone, even if these numbers appear on a Do Not Call or other non-solicitation registry). You are responsible for any fees charged by you communications provider for phone, text, or email communications that Developer sends to you.</p>
<h2>9. Compliance with privacy laws</h2>
<p>The App Provider makes the following additional commitments, representations, and warranties to you, Merchant:</p>
<p>9.1 The App Provider will only process Merchant Data and Personal Information on behalf of, and as Service Provider of, the Merchant, and not collect, retain, use, or disclose that data for any purpose other than to perform the App Provider's obligations under this Agreement, as permitted under CCPA and other applicable privacy and data protection laws (collectively, "Privacy Laws"). In no event will the App Provider "sell" (as defined by Privacy Laws) any such personal information.</p>
<p>9.2 The App Provider will not collect, use, retain, disclose, sell, or otherwise make Merchant Data or Personal Information available for App Provider's own commercial purposes or in a way that does not comply with the CCPA or other Privacy Laws.</p>
<p>9.3 App Provider will limit personal information collection, use, retention, and disclosure to activities reasonably necessary and proportionate to provide the Services set forth in the Agreement or another compatible operational purpose.</p>
<h2>10. Data subject rights &mdash; assistance with requests</h2>
<p>10.1 App Provider will reasonably cooperate and assist Merchant with meeting Merchant's CCPA and Privacy Law compliance obligations and respond to CCPA-related inquiries, including responding to verifiable consumer requests, taking into account, the nature of App Provider's processing, and the information available to App Provider. App Provider will make available to Merchant, in a manner consistent with the functionality of the Service and App Provider's role as a Service Provider of Personal Information of data subjects, the ability to fulfill data subject requests to exercise their rights under Privacy Laws.</p>
<p>10.2 If App Provider receives a request from Merchant's data subject to exercise one or more of its rights under Privacy Laws in connection with the Services, App Provider will redirect the data subject to make its request directly to Merchant. Merchant will be responsible for responding to any such request including, where possible, by using the functionality of the Services. App Provider shall comply with reasonable requests by Merchant to assist with Merchant's response to such a data subject request.</p>
<p>10.3 App Provider must notify the Merchant immediately if it receives any complaint, notice, or communication that directly or indirectly relates either party's compliance with Privacy Laws relating to provisioning of the Services.</p>
<h2>11. General</h2>
<p>11.1 You represent and warrant that you have authority to enter into this Agreement, creating performance obligations that are legally enforceable against you.</p>
<p>11.2 Developer may modify this Agreement from time-to-time and will provide you with notice when these modifications occur (notification may be through the App, email, a website, changes to the date shown at the top of this Agreement, or other electronic means). Your continued use of the App indicates your acceptance of any modifications to this Agreement. You must stop using and uninstall the App if you do not agree to any modifications that are made to this Agreement.</p>
<p>11.3 Each of us will comply with the laws, rules, and regulations (together, <strong>Laws</strong>) that apply to our respective performance under this Agreement; including, without limitation, laws related to the collection and use of consumer information obtained via the App. You will follow the requirements of all user documentation provided for the App. You will not use your App to access, store, or transmit materials that are tortious, libelous, or offensive; contain malicious code, viruses, time bombs, Trojan horses, bots, scrips or other programs; or infringe third parties' intellectual property rights.</p>
<p>11.4 This Agreement is governed by New York law, without regard to its conflicts or choice of law statutes. The courts in or for Suffolk County, New York are proper venue for any proceedings in connection with this Agreement. <strong>Both of us waive our rights to a trial by jury in connection with this Agreement.</strong></p>
<p>11.5 This is the entire agreement between us, and supersedes any prior agreements related to its subject matter. Any sections or terms of this Agreement that are, or become, invalid or unenforceable will be severed; and the remaining terms will continue in effect. Developer is not waiving any of its rights under this Agreement if it delays their exercise or fails to exercise them. We are independent contractors. This Agreement does not create an agency, partnership, or joint venture of any kind.</p>
<p>11.6 You may not assign this Agreement without Developer's written consent, which assignment is voidable by the Developer; however, Developer may assign this Agreement without notice to you or your consent.</p>
<p>11.7 You may contact Developer at: MapleKiosk Inc., <a>dev [at] maplekiosk.ca</a>. [Mailing address and phone number to be added before submission.]</p>
<div><strong>Note for Canadian merchants.</strong> MapleKiosk Inc. is based in Canada. While this Agreement is governed by New York law as set out in Section 11.4, nothing in this Agreement limits any non-waivable rights or protections available to you under applicable Canadian federal or provincial law, including the <em>Personal Information Protection and Electronic Documents Act</em> (PIPEDA) and equivalent provincial privacy legislation.
</div>
`

export const PRIVACY_TITLE =
  "Privacy Policy"
export const PRIVACY_DATE = "Effective date: July 22, 2026"
export const PRIVACY_HTML = `
<p>This "Privacy Policy" explains how MapleKiosk Inc. ("<strong>Company</strong>" or "<strong>we</strong>") collects, uses, discloses, and otherwise processes personal data on behalf of our customers &ndash; typically, merchants (any, a "<strong>Merchant</strong>") &ndash; in connection with our application, MapleKiosk, which runs on the Clover Point of Sale system ("<strong>Clover POS</strong>"). This Privacy Policy does not apply to Company's privacy practices in any other context.</p>
<p>Company's processing of personal data in connection with our application is governed by this Privacy Policy and our agreements with Merchants. In the event of any conflict between this Privacy Policy and a customer agreement, the customer agreement will control to the extent permitted by applicable law.</p>
<p>This Privacy Policy is not a substitute for any privacy policy that a Merchant may be required to provide to their customers, personnel, or other individuals.</p>
<h2>Information we collect</h2>
<p>Our application collects a limited set of information. The information we collect is primarily about the Merchant's own business and account, together with order and item data that does not identify individual consumers, and &mdash; only where a Merchant uses our booking features &mdash; limited contact details that a customer chooses to provide to make a booking or reservation. The specific information we receive may vary by Merchant.</p>
<h3>Merchant business and account information</h3>
<p>When a Merchant installs and uses our application, we collect information about the Merchant's business and account, which may include the business name, the owner's or a contact's name, email address, phone number, business or store address, and the Clover merchant identifier associated with the installation.</p>
<h3>Order and item information</h3>
<p>We collect information about orders and items processed through the Merchant's Clover POS, such as products, menu items, order totals, transaction amounts, and the date and time of a transaction. This information relates to the Merchant's operations and does not, by itself, identify the Merchant's customers. <strong>We do not receive or store payment card numbers, cardholder names, or other cardholder or payment-card data.</strong> Payment card information is handled by Clover and its payment processors, not by us.</p>
<h3>Booking and reservation details a customer provides</h3>
<p>Where a Merchant uses our booking or reservation features, we collect the contact details that a customer chooses to provide in order to request or confirm a booking &mdash; typically a name and an email address and/or phone number. We use these details only to facilitate the booking or reservation for the Merchant. We do not collect other consumer personal data through the application.</p>
<h3>Information we do not collect</h3>
<p>We do not collect information about a Merchant's personnel or employees (for example, we do not collect clock-in and clock-out times, tips earned, shifts, or wage information). We do not collect payment card or cardholder data, and we do not build consumer profiles or use consumer data for our own marketing.</p>
<h2>How we use the information we collect</h2>
<p>We use the information we collect to provide our services and the functionality of our application to Merchants: to set up and administer the Merchant's account, to manage the Merchant's product or menu catalog and orders, to facilitate appointments and reservations (including any booking or reservation contact details a customer provides), and to provide AI-assisted reception and booking services on the Merchant's behalf.</p>
<p>We may also use personal data for related internal purposes, including:</p>
<ul><li>To provide information about the application, such as important updates or changes to the application and security alerts</li>
<li>To measure performance of and improve the application</li>
<li>To respond to inquiries, complaints, and requests for customer support</li></ul>
<p>In addition, Company may use personal data as we believe necessary or appropriate to (a) comply with applicable laws and lawful requests and legal processes, such as to respond to subpoenas or requests from government authorities; (b) enforce the terms and conditions that govern our application; (c) protect our rights, privacy, safety or property, and/or that of you or others; and (d) protect, investigate and deter against fraudulent, harmful, unauthorized, unethical or illegal activity.</p>
<h2>How we share information</h2>
<p>We do not sell your personal data, and we do not share or disclose it to third parties for our own or any third party's commercial purposes. We do not provide personal data to third-party advertisers, data brokers, or marketers. The only circumstances in which information is made available to others are:</p>
<ul><li><strong>With the Merchant.</strong> We make available to the Merchant the information we hold for or about that Merchant, including any booking or reservation details a customer provided for that Merchant.</li>
<li><strong>The Clover platform.</strong> Because our application runs on the Clover POS, information processed through the application may reside on or pass through the Clover platform, which is operated by Clover subject to Clover's Privacy Notice, available at <a href="https://www.clover.com/privacy-policy">clover.com/privacy-policy</a>.</li>
<li><strong>When required by law.</strong> We may disclose information to government or law enforcement officials or others where we believe it is necessary or appropriate to comply with applicable laws, lawful requests, and legal process, or to protect the rights, privacy, safety, or property of MapleKiosk, our Merchants, or others.</li></ul>
<p>If Company is ever involved in a merger, acquisition, reorganization, sale of assets, or bankruptcy, information may be transferred as part of that transaction; in that event we will make reasonable efforts to require the recipient to honor this Privacy Policy.</p>
<h2>Your rights and choices</h2>
<h3>Data subject rights</h3>
<p>To the extent that applicable law provides individuals with rights pertaining to their personal information, such as to review and request changes to their personal information, individuals should contact the Merchant with any requests pertaining to the Merchant's use of our application. To the extent that Clover is responsible for responding to data subject rights requests under applicable law, individuals may contact Clover with applicable requests as explained in Clover's Privacy Notice, <a href="https://www.clover.com/privacy-policy">https://www.clover.com/privacy-policy</a>. Company will assist a Merchant, or Clover, as applicable, in responding to such requests subject to our contract with a Merchant or Clover.</p>
<h3>Complaints</h3>
<p>If you have a complaint about our handling of personal data, you may contact us via the contact information provided below.</p>
<h3>Updates</h3>
<p>We reserve the right to modify this Privacy Policy at any time. We will notify you of updates by updating the date of this Privacy Policy.</p>
<h2>Contact us</h2>
<p>You may contact us with any questions, comments, or complaints, about this Privacy Policy or our privacy practices via: MapleKiosk Inc., <a>dev [at] maplekiosk.ca</a>. [Mailing address and phone number to be added before submission.]</p>
<h2>Additional Information for Merchants Located in Europe</h2>
<h3>Controller and processor roles</h3>
<p>For any personal data we process on a Merchant's behalf through the application &mdash; such as the booking or reservation contact details a customer provides &mdash; Company acts as a data processor and the Merchant is the controller. For the Merchant's own business-account and contact information that we use to provide and administer our services to the Merchant, Company acts as a controller. Clover is also a controller of personal data in some circumstances. Clover's Privacy Notice is available at <a href="https://www.clover.com/privacy-policy">https://www.clover.com/privacy-policy</a>.</p>
<h3>Legal basis for processing</h3>
<p>Company processes personal data as directed or permitted by the Merchant that uses our application. The Merchant is responsible for establishing a legal basis for our processing of personal data for or on behalf of the Merchant.</p>
<h3>Cross border data transfer</h3>
<p>When we transfer personal data outside of Europe (or the UK) to countries not deemed by the European Commission to provide an adequate level of protection for personal data, we make the transfer pursuant to one of the following transfer mechanisms:</p>
<ul><li>A contract approved by the European Commission (sometimes called "Model Clauses" or "Standard Contractual Clauses");</li>
<li>The recipient's Binding Corporate Rules;</li>
<li>The consent of the individual to whom the personal data relates; or</li>
<li>Other mechanisms or legal grounds as may be permitted under applicable European law.</li></ul>
<p>You may contact us with questions about our transfer mechanism.</p>
<h3>Data retention</h3>
<p>Subject to our agreement with a Merchant, Company retains personal data for as long as necessary to (a) provide our products and services; (b) comply with legal obligations; (c) resolve disputes; and (d) enforce the terms of any agreement we may have with a Merchant. You may contact us for additional information about our data retention practices in connection with the application.</p>
<h3>Data subject rights</h3>
<p>Under certain circumstances, data subjects in Europe and the UK have certain rights relating to their personal data, which include the rights to request from the Controller (a) access to the data subject's personal data; (b) correction of incomplete or inaccurate personal data; (c) erasure of personal data; (d) restriction of processing concerning the data subject; and (e) that the controller provide a copy of the data subject's personal data that the data subject provided to the controller in a structured, commonly used and machine-readable format. Data subjects may also object to a controller's processing of personal data under certain circumstances. Where processing is based on a data subject's consent, the data subject has the right to withdraw consent at any time; however, the withdrawal of consent will not affect the lawfulness of processing based on consent before its withdrawal. Data subjects may also file a complaint with a supervisory authority. You may view contact information for supervisory authorities at <a href="https://edpb.europa.eu/about-edpb/board/members_en">edpb.europa.eu/about-edpb/board/members_en</a>. Data subjects in Europe or the UK should direct any rights request to the appropriate Controller.</p>
<h2>Your California privacy rights</h2>
<p>As a California resident, you have the rights listed below. However, these rights are not absolute, and we may decline your request as permitted by the CCPA.</p>
<ul><li><strong>Information.</strong> You can request the following information about how we have collected and used your Personal Information during the past 12 months: the categories of Personal Information that we have collected; the categories of sources from which we collected Personal Information; the business or commercial purpose for collecting and/or selling Personal Information; the categories of third parties with whom we share Personal Information; whether we have disclosed your Personal Information for a business purpose, and if so, the categories of Personal Information received by each category of recipient; and whether we've sold your Personal Information; and, if so, the categories of Personal Information received by each category of recipient.</li>
<li><strong>Access.</strong> You can request a copy of the Personal Information that we maintain about you.</li>
<li><strong>Deletion.</strong> You can ask us to delete the Personal Information that we maintain about you.</li>
<li><strong>Nondiscrimination.</strong> You are entitled to exercise the rights described above free from discrimination. This means that we will not penalize you for exercising your rights by taking actions such as by denying you goods or services, increasing the price/rate of goods or services, decreasing the service quality, or suggesting that we may penalize you as described above for exercising your rights. However, the CCPA allows us to charge you a different price or provide a different service quality if that difference is reasonably related to the value of the Personal Information we are unable to use.</li></ul>
<h3>How to exercise your rights</h3>
<p>You can request to exercise your information, access and deletion rights in the following ways:</p>
<ul><li>Email us at <a>dev [at] maplekiosk.ca</a>, or call our toll-free number [toll-free number to be added before submission].</li>
<li><strong>Identity verification.</strong> The CCPA requires us to verify the identity of the individual submitting the request before providing a substantive response to the request. A request must be provided with sufficient detail to allow us to understand, evaluate and respond. The requester must provide sufficient information to allow us to reasonably verify that the individual is the person about whom we collected information. A request may also be made on behalf of your child under 13.</li>
<li><strong>Authorized agents.</strong> California residents can empower an "authorized agent" to submit requests on their behalf. We may require the authorized agent to have a written authorization confirming that authority.</li></ul>
<h3>Sale of personal information</h3>
<p>We do not sell or share (as those terms are defined under the CCPA, including "sharing" for cross-context behavioral advertising) your Personal Information to or with third parties. In the preceding twelve (12) months, we have not sold or shared any personal information.</p>
<h3>Personal information that we collect, use and share</h3>
<p>The chart below summarizes our collection, use and sharing of Personal Information during the last 12 months before the effective date of this Privacy Policy. We describe the sources through which we collect your Personal Information in the section above titled Information we collect, and describe the purposes for which we collect, use and share this information in the sections above titled How we use the information we collect and How we share information.</p>
<div><table><thead><tr><th>Category (see the glossary below for definitions)</th>
<th>Do we collect this information?</th>
<th>Do we share this information for business purposes?</th></tr></thead>
<tbody><tr><td>Identifiers</td><td>Yes</td><td>No</td></tr>
<tr><td>Online Identifiers</td><td>No</td><td>No</td></tr>
<tr><td>Protected Classification Characteristics</td><td>No</td><td>No</td></tr>
<tr><td>Commercial Information</td><td>Yes</td><td>No</td></tr>
<tr><td>Biometric Information</td><td>No</td><td>No</td></tr>
<tr><td>Internet or Network Information</td><td>No</td><td>No</td></tr>
<tr><td>Geolocation Data</td><td>No</td><td>No</td></tr>
<tr><td>Sensory Information</td><td>No</td><td>No</td></tr>
<tr><td>Professional or Employment Information</td><td>No</td><td>No</td></tr>
<tr><td>Education Information</td><td>No</td><td>No</td></tr>
<tr><td>Inferences</td><td>No</td><td>No</td></tr>
<tr><td>Financial Information</td><td>No</td><td>No</td></tr>
<tr><td>Medical Information</td><td>No</td><td>No</td></tr></tbody></table></div>
<h3>Glossary</h3>
<ul><li><strong>Biometric Information.</strong> An individual's physiological, biological or behavioral characteristics, including DNA, that can be used to establish an individual's identity, such as imagery of the iris, retina, fingerprint, face, hand, palm, vein patterns, and voice recordings, as well as keystroke, gait, sleep, health, or exercise data that contain identifying information.</li>
<li><strong>Commercial Information / Transaction History.</strong> Products or services purchased, obtained, or considered, or other purchasing or consuming histories or tendencies.</li>
<li><strong>Financial Information.</strong> Bank account number, debit or credit card numbers, insurance policy number, and other financial information.</li>
<li><strong>Geolocation Data.</strong> Precise location, e.g., derived from GPS coordinates or telemetry data.</li>
<li><strong>Identifiers.</strong> Real name, alias, postal address, unique personal identifier, customer number, email address, account name and other similar identifiers.</li>
<li><strong>Internet or Network Information.</strong> Browsing history, search history, and information regarding a consumer's interaction with an Internet website, application, or advertisement.</li>
<li><strong>Online Identifiers.</strong> An online identifier or other persistent identifier that can be used to recognize a person, family or device over time and across different services, including device identifiers, IP addresses, cookies, beacons, pixel tags, mobile ad identifiers, or similar technology.</li>
<li><strong>Professional or Employment Information.</strong> Information relating to a person's current, past or prospective employment or professional experience, and educational background.</li>
<li><strong>Protected Classification Characteristics.</strong> Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex (including gender, gender identity, gender expression, pregnancy or childbirth and related medical conditions), sexual orientation, veteran or military status, and genetic information.</li>
<li><strong>Sensory Information.</strong> Audio, electronic, visual, thermal, olfactory, or similar information.</li>
<li><strong>Medical Information.</strong> Personal information about an individual's health or healthcare, including health insurance information.</li></ul>
<div><strong>Additional information for Canadian merchants and customers.</strong> MapleKiosk Inc. is based in Canada and handles personal information in accordance with the <em>Personal Information Protection and Electronic Documents Act</em> (PIPEDA) and applicable provincial privacy legislation. Individuals in Canada have the right to access and request correction of their personal information and to withdraw consent, subject to legal and contractual restrictions. Because we act on behalf of Merchants, individuals should direct such requests to the relevant Merchant; we will assist the Merchant in responding. You may also contact us at <a>dev [at] maplekiosk.ca</a>, and you may file a complaint with the Office of the Privacy Commissioner of Canada.
</div>
`
