"""Write the isometric drawings into the site.

    python3 tools/iso/export.py

Outputs:
  public/iso/<name>.svg                 static figures, used with <img>
  src/components/iso/scenes/<name>.ts   interactive scenes: { viewBox, svg, markers, labels }
"""
import json
import math
import pathlib

import iso_lib as L
import models as m
import scenes

ROOT = pathlib.Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public" / "iso"
SCENES = ROOT / "src" / "components" / "iso" / "scenes"
PIN = 34
FIG_STYLE = "<style>*{vector-effect:non-scaling-stroke}text{font-family:'DM Mono',ui-monospace,monospace}</style>"


def bounds(parts, extra_pts=()):
    xs, ys = [], []
    for p in parts:
        b = L.sbbox(p)
        xs += [b[0], b[2]]
        ys += [b[1], b[3]]
    for x, y in extra_pts:
        xs.append(x)
        ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


def viewbox(b, pad):
    return (round(b[0] - pad, 1), round(b[1] - pad, 1), round(b[2] - b[0] + 2 * pad, 1), round(b[3] - b[1] + 2 * pad, 1))


def pct(pt, vb):
    return round((pt[0] - vb[0]) / vb[2] * 100, 2), round((pt[1] - vb[1]) / vb[3] * 100, 2)


def door_arc(hinge, closed, opened):
    r = math.dist(hinge, closed)
    a0 = math.atan2(opened[1] - hinge[1], opened[0] - hinge[0])
    a1 = math.atan2(closed[1] - hinge[1], closed[0] - hinge[0])
    if a1 - a0 > math.pi:
        a1 -= 2 * math.pi
    if a0 - a1 > math.pi:
        a1 += 2 * math.pi
    arc = [L.P(hinge[0] + r * math.cos(a0 + (a1 - a0) * t / 16), hinge[1] + r * math.sin(a0 + (a1 - a0) * t / 16), 0) for t in range(17)]
    return f'<polyline fill="none" stroke="{L.INK}" stroke-width="1" points="{L.pts([L.P(hinge[0], hinge[1], 0)] + arc)}"/>'


def ts_module(name, vb, inner, markers, labels):
    data = {
        "viewBox": " ".join(str(v) for v in vb),
        "svg": inner,
        "markers": [{"id": k, "x": x, "y": y} for k, (x, y) in sorted(markers.items())],
        "labels": [{"key": k, "x": x, "y": y} for k, (x, y) in labels.items()],
    }
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return f"// Generated by tools/iso/export.py. Do not edit.\nexport const {name} = {body} as const\n"


def plan(name, build, door):
    parts, markers, labels = build()
    W, D = 900, 560
    slab = dict(t="box", x0=-scenes.T, y0=-scenes.T, x1=W + scenes.T, y1=D + scenes.T, z0=-18, z1=0, kind="slab", obj=None, decals=[])
    body = [L.draw_box(slab), door_arc(*door), L.render(parts)]
    tops = {}
    for n, (x, y, z, *pin) in markers.items():
        a = L.P(x, y, z)
        top = (a[0], a[1] - (pin[0] if pin else PIN))
        body.append(f'<g class="pin p{n}"><line x1="{a[0]:.1f}" y1="{a[1]:.1f}" x2="{top[0]:.1f}" y2="{top[1]:.1f}" stroke="{L.INK}" stroke-width="1"/>'
                    f'<circle cx="{a[0]:.1f}" cy="{a[1]:.1f}" r="2.5" fill="{L.INK}" stroke="none"/></g>')
        tops[n] = top
    vb = viewbox(bounds(parts + [slab], tops.values()), 24)
    mk = {n: pct(t, vb) for n, t in tops.items()}
    lb = {k: pct(L.P(*a), vb) for k, a in labels.items()}
    return ts_module(name, vb, "".join(body), mk, lb)


def board():
    size = 3 * scenes.CELL + 2 * scenes.GAP
    plate = dict(t="box", x0=-18, y0=-18, x1=size + 18, y1=size + 18, z0=-22, z1=0, kind="slab", obj=None, decals=[])
    body = [L.draw_box(plate)]
    cells = {}
    for cx in range(3):
        for cy in range(3):
            ox, oy = cx * (scenes.CELL + scenes.GAP), cy * (scenes.CELL + scenes.GAP)
            cells[(cx, cy)] = (ox, oy)
            q = [L.P(ox, oy, 0), L.P(ox + scenes.CELL, oy, 0), L.P(ox + scenes.CELL, oy + scenes.CELL, 0), L.P(ox, oy + scenes.CELL, 0)]
            body.append(f'<polygon points="{L.pts(q)}" fill="none" stroke="{L.LINE}" stroke-width="1"/>')
    everything = [plate]
    pos_drawn = False
    for mid, (cx, cy) in sorted(scenes.BOARD.items(), key=lambda kv: kv[1][0] + kv[1][1]):
        if not pos_drawn and cx + cy >= 2:
            ox, oy = cells[(1, 1)]
            pos = m.register(ox + 10, oy + 6, 0)
            everything += pos
            body.append('<g class="pos">' + L.render(pos) + "</g>")
            pos_drawn = True
        ox, oy = cells[(cx, cy)]
        q = [L.P(ox + 14, oy + 14, 0), L.P(ox + 86, oy + 14, 0), L.P(ox + 86, oy + 86, 0), L.P(ox + 14, oy + 86, 0)]
        c = L.P(ox + 50, oy + 50, 0)
        plus = f"M{c[0]-9:.1f} {c[1]:.1f}H{c[0]+9:.1f}M{c[0]:.1f} {c[1]-5:.1f}V{c[1]+5:.1f}"
        body.append(f'<g class="slot" data-slot="{mid}"><polygon points="{L.pts(q)}" fill="none" stroke="{L.MUTED}" stroke-width="1" stroke-dasharray="4 4"/>'
                    f'<path d="{plus}" stroke="{L.MUTED}" stroke-width="1.2"/></g>')
        tile = scenes.board_tile(mid, ox, oy)
        everything += tile
        body.append(f'<g class="tile" data-tile="{mid}">' + L.render(tile) + "</g>")
    vb = viewbox(bounds(everything), 12)
    return ts_module("board", vb, "".join(body), {}, {})


def figure(parts):
    b = bounds(parts)
    vb = viewbox(b, 6)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb[0]} {vb[1]} {vb[2]} {vb[3]}" width="{vb[2]:.0f}" height="{vb[3]:.0f}">'
            f"{FIG_STYLE}{L.render(parts)}</svg>\n")


def main():
    PUBLIC.mkdir(parents=True, exist_ok=True)
    SCENES.mkdir(parents=True, exist_ok=True)
    for name, build in scenes.FIGURES.items():
        (PUBLIC / f"{name}.svg").write_text(figure(build()))
    (SCENES / "board.ts").write_text(board())
    (SCENES / "restaurant.ts").write_text(plan("restaurantPlan", scenes.restaurant, ((460, 560), (380, 560), (460, 480))))
    (SCENES / "salon.ts").write_text(plan("salonPlan", scenes.salon, ((780, 560), (700, 560), (780, 480))))
    print(f"wrote {len(scenes.FIGURES)} figures and 3 scenes")


if __name__ == "__main__":
    main()
